import { expect, it } from "@effect/vitest"
import { Effect, Record, Result, Schema, pipe } from "effect"
import { Form } from "effect-domains/form"
import { Requests } from "effect-domains/requests"

it("a replaced request cannot publish an error or finish its successor", () => {
  const empty = Requests.empty()
  const first = Requests.start(empty, "books")
  const second = Requests.start(first.state, "books")
  const afterLateFailure = Requests.fail(second.state, first.request, "old failure")
  const afterLateSuccess = Requests.succeed(afterLateFailure, first.request)
  const acceptsOld = Requests.accepts(afterLateSuccess, first.request)
  const acceptsNew = Requests.accepts(afterLateSuccess, second.request)
  const remainsPending = Requests.pending(afterLateSuccess, "books")
  expect(acceptsOld).toBe(false)
  expect(acceptsNew).toBe(true)
  expect(remainsPending).toBe(true)
  expect(afterLateSuccess.errors).toEqual({})
  const failed = Requests.fail(afterLateSuccess, second.request, "current failure")
  const failedPending = Requests.pending(failed, "books")
  expect(failedPending).toBe(false)
  expect(failed.errors).toEqual({ books: "current failure" })
})

it("reset rejects prior-session results without finishing independent current queries", () => {
  const empty = Requests.empty()
  const previous = Requests.start(empty, "list")
  const reset = Requests.reset(previous.state)
  const current = Requests.start(reset, "list")
  const totals = Requests.start(current.state, "totals")
  const stale = Requests.succeed(totals.state, previous.request)
  const acceptsPrevious = Requests.accepts(stale, previous.request)
  const acceptsCurrent = Requests.accepts(stale, current.request)
  expect(acceptsPrevious).toBe(false)
  expect(acceptsCurrent).toBe(true)
  const listed = Requests.succeed(stale, current.request)
  const listPending = Requests.pending(listed, "list")
  const totalsPending = Requests.pending(listed, "totals")
  const acceptsTotals = Requests.accepts(listed, totals.request)
  expect(listPending).toBe(false)
  expect(totalsPending).toBe(true)
  expect(acceptsTotals).toBe(true)
})

it("invalidating one query rejects its late result while preserving other work", () => {
  const empty = Requests.empty()
  const listed = Requests.start(empty, "list")
  const saving = Requests.start(listed.state, "save")
  const changed = Requests.invalidate(saving.state, "list")
  const acceptsInvalidated = Requests.accepts(changed, listed.request)
  const invalidatedPending = Requests.pending(changed, "list")
  const acceptsSave = Requests.accepts(changed, saving.request)
  expect(acceptsInvalidated).toBe(false)
  expect(invalidatedPending).toBe(false)
  expect(acceptsSave).toBe(true)
  const refreshed = Requests.start(changed, "list")
  const acceptsOld = Requests.accepts(refreshed.state, listed.request)
  const acceptsRefreshed = Requests.accepts(refreshed.state, refreshed.request)
  expect(acceptsOld).toBe(false)
  expect(acceptsRefreshed).toBe(true)
})

const QuantitySchema = Schema.Int.check(Schema.isGreaterThan(0))
const QuantityFormSchema = Schema.Struct({ quantity: Form.integer(QuantitySchema) })
const decodeQuantity = Schema.decodeUnknownEffect(QuantityFormSchema)

it.effect("integer forms reject truncation and preserve target validation paths", Effect.fn("ExampleWeb.testIntegerParsing")(function* () {
  const accepted = yield* decodeQuantity({ quantity: " 12 " })
  expect(accepted.quantity).toBe(12)
  const fraction = yield* pipe(decodeQuantity({ quantity: "12.5" }), Effect.result)
  const fractionRejected = Result.isFailure(fraction)
  expect(fractionRejected).toBe(true)
  const nonpositive = yield* pipe(decodeQuantity({ quantity: "0" }), Effect.flip)
  const fields = pipe(nonpositive, Form.errors, Record.keys)
  expect(fields).toEqual(["quantity"])
}))

it.effect("integer forms reject precision loss and nullable text is an explicit conversion", Effect.fn("ExampleWeb.testNullableBoundaries")(function* () {
  const unsafe = yield* pipe(decodeQuantity({ quantity: "9007199254740993" }), Effect.result)
  const unsafeRejected = Result.isFailure(unsafe)
  expect(unsafeRejected).toBe(true)
  const NoteSchema = Form.nullableText(Schema.NonEmptyString)
  const decode = Schema.decodeUnknownEffect(NoteSchema)
  const blank = yield* decode("   ")
  const note = yield* decode("  site note  ")
  const encoded = yield* Schema.encodeEffect(NoteSchema)(null)
  expect(blank).toBeNull()
  expect(note).toBe("site note")
  expect(encoded).toBe("")
}))
