import { Option, Record } from "effect"
import { DefaultTableIdentifierSchema } from "./schemas.ts"
import { TableFieldSchema, type TableField } from "./schemas.ts"

/**
 *
 * Scope: public
 *
 * When to use: Schema derivation needs the generated identifier field because
 * tables without domain identity receive physical UUIDv7 identity.
 *
 * Example:
 * ```ts
 * import { DefaultIdentifierFields } from "effect-domains/table/constants"
 *
 * const value = DefaultIdentifierFields.id
 * ```
 *
 */
export const DefaultIdentifierFields = Record.singleton(
  "id",
  DefaultTableIdentifierSchema,
)

/**
 *
 * Scope: public
 *
 * When to use: Adapter metadata needs to mark an authored field because
 * authored values must never be generated mechanically.
 *
 * Example:
 * ```ts
 * import { NoGeneration } from "effect-domains/table/constants"
 *
 * const value = NoGeneration
 * ```
 *
 */
export const NoGeneration = Option.none<"uuidv7">()

const GeneratedIdentifierGeneration = Option.some<"uuidv7">("uuidv7")

/**
 *
 * Scope: public
 *
 * When to use: Adapter metadata needs the default identifier column because its
 * UUIDv7 value is generated by persistence.
 *
 * Example:
 * ```ts
 * import { DefaultIdentifierField } from "effect-domains/table/constants"
 *
 * const value = DefaultIdentifierField.name
 * ```
 *
 */
export const DefaultIdentifierField = TableFieldSchema.make({
  name: "id",
  scalar: "string",
  generation: GeneratedIdentifierGeneration,
})
